/**
 * This is automatically generated by sprout plug-in.
 */
package com.app.ildong.common.util;

import java.util.List;
import java.util.Map;

import org.apache.commons.collections.MapUtils;
import org.apache.tiles.Attribute;
import org.apache.tiles.AttributeContext;
import org.apache.tiles.preparer.ViewPreparer;
import org.apache.tiles.request.Request;
import org.springframework.beans.factory.annotation.Autowired;

import com.app.ildong.common.dao.MenuPreparerDAO;
import com.app.ildong.common.vo.MenuPreparerVO;

public class MenuPreparerUtil implements ViewPreparer{
        
    @Autowired
    private MenuPreparerDAO menuPreparerDAO;
    
    /**
     * @see org.apache.tiles.preparer.ViewPreparer#execute(org.apache.tiles.request.Request, org.apache.tiles.AttributeContext)
     */
    @Override
    public void execute(Request request, AttributeContext attributeContext) {
        // 권한에 따른 MenuList
        attributeContext.putAttribute("menuList", new Attribute(getMenuListByRole("ROLE_ADMIN")), true);
        
        // Default Menu
        Map<String, String> param = request.getParam();
        String curMenuId = MapUtils.getString(param, "curMenuId", "");
        String parentMenuId = MapUtils.getString(param, "parentMenuId", ""); 
        String topMenuId = MapUtils.getString(param, "topMenuId", "M01");
        
        attributeContext.putAttribute("topMenuId", new Attribute(topMenuId), true);
        attributeContext.putAttribute("parentMenuId", new Attribute(parentMenuId), true);
        attributeContext.putAttribute("curMenuId", new Attribute(curMenuId), true);
    }
    
    private List<MenuPreparerVO> getMenuListByRole(String roleId) {
        return menuPreparerDAO.selectMenuListByRole(roleId);
    }
        
}