/**
 * This is automatically generated by sprout plug-in.
 */
package com.app.ildong.common.controller;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

@Controller
public class LocaleController {
    
    private Logger logger=LoggerFactory.getLogger(LocaleController.class);
    
    /**
     * changeLocale
     * 게시판 국제화 처리
     * Locale 변경 후, Sample Main으로 이동(로케일만 Inteceptor 에서 변경하고 메인 페이지로 이동)  
     * @param locale
     * @return String
     */
    @RequestMapping(value = "/changeLocale")
    public String changeLocale(@RequestParam(required = false) String locale) {
        if(logger.isDebugEnabled()){
            logger.debug("locale is changed : {}" , LocaleContextHolder.getLocale().toString());
            logger.debug("locale param \"locale\", value : {}" , locale);
        }
        return "redirect:/";
    }

}