/**
 * This is automatically generated by sprout plug-in.
 */
package com.app.ildong.common.controller;

import java.util.HashMap;
import java.util.Map;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

@Controller
@RequestMapping("/menuPreparer")
public class MenuPreparerController {

    
    /**
     * init
     * "/" Path에 대해서 메뉴 Info 화면으로 이동.
     * @param model
     * @return String
     */
    @RequestMapping({"/", ""})
    public String init(Model model) {
        return "redirect:/";
    }
    
    
    /**
     * getMenuInfo
     * 메뉴의 상세 정보 화면으로 이동
     * @param curMenuId     : 현재 메뉴 Id
     * @param parentMenuId  : 부모 메뉴 Id
     * @param topMenuId     : 최상위 메뉴 Id
     * @param model
     * @return String
     */
    @RequestMapping(value={"/bcm/mng/{path}", "/bcm/mtr/{path}"})
    public String getMenuPreparerInfo(@RequestParam(required = true) String curMenuId, @RequestParam(required = true) String parentMenuId, @RequestParam(required = true) String topMenuId, Model model) {
        Map<String, String> menuInfo = new HashMap<String, String>();
        menuInfo.put("topMenuId", topMenuId);
        menuInfo.put("parentMenuId", parentMenuId);
        menuInfo.put("curMenuId", curMenuId);
        
        model.addAttribute("menuInfo", menuInfo);
        return "menu/menuInfo";
    }
    
    @RequestMapping(value={"/bcm/auth/**"})
    public String methodAnnotationAuthorityCheck() {
    	return "authority/authorityCheck";
    }
    
}