/**
 * This is automatically generated by sprout plug-in.
 */
package com.app.ildong.common.vo;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;


@JsonIgnoreProperties(ignoreUnknown = true)
public class MenuPreparerVO {
    
    private String menuId;
    private String parentMenuId;
    private String menuCategory;
    private String menuDepthNo;
    private String displayIndex;
    private String useFlag;
    private String regUserId;
    private String regDate;
    private String updateUserId;
    private String updateDate;
    private String menuName;
    private String pageUri;
    private String description;
    
    public String getMenuId() {
        return menuId;
    }
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }
    public String getParentMenuId() {
        return parentMenuId;
    }
    public void setParentMenuId(String parentMenuId) {
        this.parentMenuId = parentMenuId;
    }
    public String getMenuCategory() {
        return menuCategory;
    }
    public void setMenuCategory(String menuCategory) {
        this.menuCategory = menuCategory;
    }
    public String getMenuDepthNo() {
        return menuDepthNo;
    }
    public void setMenuDepthNo(String menuDepthNo) {
        this.menuDepthNo = menuDepthNo;
    }
    public String getDisplayIndex() {
        return displayIndex;
    }
    public void setDisplayIndex(String displayIndex) {
        this.displayIndex = displayIndex;
    }
    public String getUseFlag() {
        return useFlag;
    }
    public void setUseFlag(String useFlag) {
        this.useFlag = useFlag;
    }
    public String getRegUserId() {
        return regUserId;
    }
    public void setRegUserId(String regUserId) {
        this.regUserId = regUserId;
    }
    public String getRegDate() {
        return regDate;
    }
    public void setRegDate(String regDate) {
        this.regDate = regDate;
    }
    public String getUpdateUserId() {
        return updateUserId;
    }
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }
    public String getUpdateDate() {
        return updateDate;
    }
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }
    public String getMenuName() {
        return menuName;
    }
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }
    public String getPageUri() {
        return pageUri;
    }
    public void setPageUri(String pageUri) {
        this.pageUri = pageUri;
    }
    public String getDescription() {
        return description;
    }
    public void setDescription(String description) {
        this.description = description;
    }
    @Override
    public String toString() {
        return "MenuVO [menuId=" + menuId + ", parentMenuId=" + parentMenuId + ", menuCategory=" + menuCategory
            + ", menuDepthNo=" + menuDepthNo + ", displayIndex=" + displayIndex + ", useFlag=" + useFlag
            + ", regUserId=" + regUserId + ", regDate=" + regDate + ", updateUserId=" + updateUserId + ", updateDate="
            + updateDate + ", menuName=" + menuName + ", pageUri=" + pageUri + ", description=" + description + "]";
    }

}