/**
 * This is automatically generated by sprout plug-in.
 */
package com.app.ildong.common.dao;

import java.util.List;

import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Repository;

import com.app.ildong.common.vo.MenuPreparerVO;

/**
 * 
 * 메뉴 구성을 위한 항목.
 * MENU_ID          : 메뉴 ID
 * PARENT_MENU_ID   : 부모메뉴 ID
 * MENU_DEPTH_NO    : 메뉴 Depth
 * MENU_NAME        : 메뉴 명
 * PAGE_URI         : 화면 이동 URI
 * ROLE_ID          : 로그인한 사용자의 권한
 * MENU_CATEGORY    : 메뉴 특성 구분 (SYS(공통), BIZ(업무))
 * 
 */
@Repository("menuPreparerDAO")
public class MenuPreparerDAO {

	@Autowired
    private SqlSessionTemplate sqlSessionTemplate;
	
	@Cacheable("menuPreparerCache")
	public List<MenuPreparerVO> selectMenuListByRole(String roleId) {
        return sqlSessionTemplate.selectList("menuPreparer.selectMenuListByRole", roleId);
    }
        
}